### ISSUE TITLE
Package name is wrong

### ISSUE THREAD

**Issue by hadley** [rstudio/sassr#1]
Clearly, _clearly_, it should be sassier

**Comment by wch** [comment]
Or sassyr.

**Comment by tmastny** [comment]
[Sassc](https://github.com/sass/sassc)r?

**Comment by rich-iannone** [comment]
SašieR. Just joking.

**Comment by schloerke** [comment]
Going to change to `sass`. _Boring_, but direct.

```r
sass::sass(INPUT)
```

**Comment by tmastny** [comment]
The only confusing part about naming it sass is that you always need to qualify which sass you are taking about. Sass could refer to the R package, the language, or the implementation.
