### ISSUE TITLE
compile_sass() should have option to specify which directory to run in when text is used

### ISSUE THREAD

**Issue by wch** [rstudio/sassr#3]
For example, suppose you do this:

```R
scss_text <- '@import "something.scss";';
compile_sass(text = scss_text)
# Error in compile_data(text, options) : 
#   Error: File to import not found or unreadable: something.scss.
#         on line 1:1 of stdin
# >> @import "something.scss";
#    ^
```

When a text string is passed in, it would be useful to be able to include files from a specified directory.

I think this can be done using `withr::with_dir()`.

**Comment by tmastny** [comment]
I believe this is already resolved with `sass_options(include_path = ".")`. Here's a working example as a unit test:
https://github.com/rstudio/sassr/blob/master/tests/testthat/test-include-paths.R#L5
